### ISSUE TITLE
Weak symbols not visible/not loaded via LD_PRELOAD when using mold linker

### ISSUE THREAD

**Issue by carlosgalvezp** [rui314/mold#1079]
Hi!

We are using mold 2.0.0 on Ubuntu 22 (GCC 11.4). We have some code that injects symbols from dynamic libraries using LD_PRELOAD. That has worked fine so far with ld and lld, but when switching to mold it stops working - the symbols are not loaded. I have reduced it to a minimal example:

```cpp
// main.cpp
extern int __attribute__((weak)) my_symbol;

int main()
{
  return my_symbol;
}
```

```cpp
// foo.cpp
int my_symbol{123};
```

Build:

```bash
if [ -z $USE_MOLD ]; then
LINK_FLAGS="-fuse-ld=lld";
else
LINK_FLAGS="-Bmold-2.0.0-x86_64-linux/libexec/mold/"
fi

g++ -fPIC         $LINK_FLAGS main.cpp -o main
g++ -fPIC -shared $LINK_FLAGS foo.cpp  -o libfoo.so
```

Run:
```
LD_PRELOAD=$(pwd)/libfoo.so ./main
```

- With lld: the output is correct (123).
- With mold, the code segfaults, because the address of `my_symbol` is 0.

Are we missing any additional flag to the compiler/linker to make this work?

Thanks!

**Comment by carlosgalvezp** [comment]
Running `readelf` on the `main` executable, I find a difference:

* With lld:
```
    29: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND my_symbol
```
* With mold:
```
    61: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND my_symbol
```

So the symbol is not registered as `WEAK` when linking with mold.

**Comment by rui314** [comment]
You made a good point but this is a difficult case. If you compile your main executable as non-PIE as below

```
g++ -no-pie -fno-PIE -fuse-ld=bfd main.cpp -o main
readelf -W --dyn-syms main
```

you wouldn't see `my_symbol` as a dynamic symbol. That means the behavior of the GNU linker is inconsistent for position-independent and position-dependent executables. I don't think that's generally a good thing and should be considered a bug rather than a feature of the GNU linker.

In mold, we consistently do not promote unresolved weak symbols in a main executable to a dynamic symbol.
