### ISSUE TITLE
osdev usecase: Can Debuginfo be loadable?

### ISSUE THREAD

**Issue by mstarodub** [rui314/mold#1194]
We're writing an operating system, and have run into an issue with the linker (currently we're using lld). We would like to provide detailed stacktraces for kernel panics, and this requires parsing DWARF debuginfo.

The `debug_*` sections need to be loaded into memory at runtime. lld does not do this, even if you explicitly mark the sections or corresponding segments as loadable in the linkerscript. 

If you use objcopy to manually mark the sections as loadable before linking, the relocations in the debuginfo are not processed with lld.

Can mold support this?

**Comment by rui314** [comment]
We probably can, but there are a few practical issues if you load DWARF debug info into memory.

1. Debug info is huge and consumes a lot of memory
2. You need to figure out how to find the beginning of each debug info section. When you are reading debug info from an executable, you can just look up the section table, but that scheme doesn't work for memory-mapped data. You probably need to mark the beginning of each section with some special symbol.

If you don't care too much about memory usage, one thing to achieve your goal might be to map your entire kernel file to a separate memory address. You can doubly-map any pages, so you can create a new LOAD segment that covers the entire file so that you can read the entire file contents from that memory address.

mold has `--spare-program-headers` option to create a placeholder in the segment table. With that, it should be trivial to add a new PT_LOAD segment to map the entire file to memory. How does this sound to you?

**Comment by mstarodub** [comment]
> Debug info is huge and consumes a lot of memory

It's a lot of memory for an embedded system, but for our usecase we don't care.

> one thing to achieve your goal might be to map your entire kernel file to a separate memory address

> How does this sound to you?

This sounds like an acceptable solution.

> With that, it should be trivial to add a new PT_LOAD segment to map the entire file to memory

How would this work in detail? Does mold already have all the required facilities?

**Comment by rui314** [comment]
Since you are writing an operating system, its loader is also written by yourself. Usually, when you load a kernel image to memory, its segments are mapped according to its program headers. Specifically, segments of type `PT_LOAD` describe the file-to-memory mapping.

You can add a spare segment using `--spare-program-headers=1`. The spare slot will have `PT_NULL` type. You want to post-process your kernel after linking to rewrite the `PT_NULL` segment with `PT_LOAD` to map the entire file to a specific memory location.

**Comment by mstarodub** [comment]
> Since you are writing an operating system, its loader is also written by yourself

We are not writing the loader, the loader is whatever bootloader we have (qemu/grub/etc).

But I see an issue with this approach now:
You have to pick a fixed physical address that needs to get hardcoded into both the code and the post-processing script. A priori you do not know: a) where the linker puts its stuff b) how much RAM you have. 
As a result, there might be conflicts due to your choice of address.

So I would actually prefer the option of loading `debug_*` sections directly (the issue there is, as you mentioned, exporting the section locations would have to be implemented to communicate these from the linker to the OS).

By the way: For the spare program headers approach, I would appreciate suggestions on implementing said post-processing script. I was thinking of using pyelftools from python. 

Thanks!

**Comment by rui314** [comment]
You don't need to hardcode the address where the entire kernel file including debug info would be mapped to. The post-processing tool can read the program header to find the the last segment and add a new segment so that the new one is next to the last one. At runtime, your kernel can read the program header (which is accessible as `__ehdr_start`) to find the location of the last segment.

**Comment by rui314** [comment]
Did it work?

**Comment by mstarodub** [comment]
Apologies for the delay. I had some time to work on this, and it turns out your proposed solution is perfectly fine.

Mold works great for my kernel; the current apis are good, and we have working stack traces now.

Thank you so much for the help!
