### ISSUE TITLE
Distribute binary releases for easier usage

### ISSUE THREAD

**Issue by Calinou** [rui314/mold#123]
With the [build-static.sh](https://github.com/rui314/mold/blob/main/build-static.sh) script, would it be possible to build statically linked mold binaries that can work on common Linux distributions?

Ensuring portability across distributions can be challenging, especially since C++20 is used. Nonetheless, a binary that runs on Ubuntu 20.04 and later, Debian stable, Fedora and Arch Linux would be a good start already. Maybe this binary could be statically linked with musl to not depend on glibc, but I don't know if that's technically possible. Using musl would allow using mold in Alpine Linux containers easily.

This would speed up the initial setup of mold on a new machine. Thanks in advance :slightly_smiling_face:

**Comment by evergreen-trading-systems** [comment]
I ran `build-static.sh`

![image](https://user-images.githubusercontent.com/4870868/139703760-01b8d40a-87cd-4aa1-9ed5-a983af600d5c.png)

How do I use this binary because https://github.com/rui314/mold/issues/26#issuecomment-804688649 doesn't work

**Comment by rui314** [comment]
@evergreen-trading-systems 
You need to run mold as `./mold` instead of `mold` if it is in the current directory.

**Comment by rui314** [comment]
I tried to write a shell script to pack a statically-linked mold binary into a tar archive along with related files, but it turned out that I need to copy lots of COPYING or LICENSE files into the archive to comply with third-party library licenses. But it is not easy to maintain such combined license file, as third-party libraries can change. I don't want to risk of unintentional license violation. So, I will avoid distributing statically-linked binary myself. Sorry for your inconvenience, but if you need a statically-linked binary, please build yourself.

**Comment by Milo123459** [comment]
Sorry for just hopping in here, what about a Docker image? I run Debian to build my Rust project and don't want to have to make and install mold everytime, an image would be helpful. Perhaps, on each new release, automatically run build-static.sh and publish to hub.docker.com
