### ISSUE TITLE
Binary linked with mold segfaults immediately

### ISSUE THREAD

**Issue by vmchale** [rui314/mold#1272]
To reproduce:

```
$ wget shakti.com/k.zip;unzip k;mold -run make
$ ./k
```

This segfaults immediately.

However,

```
$ wget shakti.com/k.zip;unzip k;make
$ ./k
```

works as expected.

**Comment by rui314** [comment]
I couldn't compile your program, and your code is obfuscated. I honestly thought that this could be a phishing attack. Could you tell me a little bit more about your program and ensure that the code compiles in a fresh ubuntu or some other major distro environment?

**Comment by vmchale** [comment]
This is Ubuntu 22.04. I installed clang-13 from [their ppa](https://apt.llvm.org/).

The code is not mine; it's from [Arthur Whitney](https://shakti.com/) (it is [typical of his style](https://github.com/tlack/b-decoded/tree/master?tab=readme-ov-file#arthur-style). It's an implementation of k, a programming language. E.g. 

```
 +/1 2 3
6
```

**Comment by rui314** [comment]
Hmm, it seems shakti.com/k.zip is just gone. It's now 404.

**Comment by mqudsi** [comment]
Download link works for me. Mirrored: 
[k.zip](https://github.com/user-attachments/files/15946148/k.zip)

**Comment by rui314** [comment]
So the issue here is that the compiler frontend passed `--dynamic-linker /lib64/ld-linux-x86-64.so.2` to mold. Since the binary is statically-linked, it doesn't need the dynamic linker. We can add a special logic to mold so that mold ignores the `--dynamic-linker` option if the dynamic linker is not needed, but I think it is more like hiding the issue rather than solving it.

You want to add `-static` to the final link line if you are creating a statically-linked executable. `-nostdlib` doesn't imply `-static`.
