### ISSUE TITLE
Proposal: split debug symbols

### ISSUE THREAD

**Issue by jzwinck** [rui314/mold#1294]
Making release builds with debug symbols (e.g. `-O2 -g`) is common and produces large executables.  It is standard industry practice to split debug symbols into a separate file which does not need to be deployed to most machines.  See https://github.com/GabrielMajeri/separate-symbols.

While the objective is well known and valuable, the process is arcane and inefficient.  Linkers produce an executable file which is immediately read back from disk using separate tools and then written to the final files.  Mold could do this better.

Benefits:
1. Ease of use for people who currently find it troublesome or aren't even aware it's possible on Linux (it's much easier using MSVC).
2. Speed.  Avoids writing and reading the full executable on disk.  Also, Mold is better at parallelism and reusing data in memory vs existing tools which are single-threaded and read (parts of) the executable multiple times.
3. Mold gains a competitive advantage over other linkers (at least until they add this, which would only be a good thing).
4. Reduced disk usage during the build by avoiding writing the large but ultimately unnecessary full executable.

Do you like this idea or see pitfalls?  Feedback very welcome.

**Comment by rui314** [comment]
I'm interested in this, not only because it's convenient but also because it could potentially improve the linker's overall speed for debug builds. Let me experiment with some ideas.

**Comment by Ext3h** [comment]
There is a slight pitfall in deciding which symbols / sections are supposed to go into which file and which is supposed to be stripped.

There's a difference between a library which is intended for open source distribution (thus the full symbol file can be made available, and the binary can be stripped to the bare minimum), a closed source library which is intended for embedding into a 3rd party process (thus the original developer needs a full symbol file to provide support, but also minimal debugging information left in the PE executable to enable the 3rd party to walk stack frames!), and a self-contained executable which can be stripped entirely (including relocation information) and everything can be placed in the symbols.

That referenced call sequence with `objcopy` covers the first case only. The second case requires a finer grained control about which section should go into which file, and that is also dependent on the actual debug format used.

Long story short, you may need more than one output file for symbols, and you need a  fine grained control where which sections goes, as well as by which naming convention the debug links / supplementary file links are set up.

---

There is a lot of prior art to consider:
https://maskray.me/blog/2022-10-30-distribution-of-debug-information

Especially `MiniDebugInfo` is something to take a look at. The `LZMA-` compressed debug section render debug symbols easily deployable, reducing the biggest pain point which is the size. This is possibly a better default choice than a split debug file for distribution channels that ***don't*** have a dedicated debug symbol server!

Routing the ***fulll*** (or by user choice: slightly less) set of debug symbols into an external file, and embedding a ***reduced*** set with `MiniDebugInfo` is a sensible choice.

`Split DWARF object files` are a no-go as they don't work with LTO by design, the linker doesn't even get to know about them. The GCC frontend e.g. doesn't even permit the combination of `-lto` with `-gsplit-dwarf` either.

---

There is also talk in other repositories about proposed linker options:
https://github.com/golang/go/issues/51692#issuecomment-1548872476

**Comment by rui314** [comment]
We don't need to support all of the use cases. For complex use cases, it would probably be better to stick with post-link editing tools such as objcopy. I'm interested in implementing this because it could speed up the normal linking by separating debug info to another file.

**Comment by jzwinck** [comment]
@Ext3h Thank you for writing all that out.  Personally I have only ever seen people using what you call the first case.  I am not sure what the difference is between your third case and first case.  I understand the motivation behind the second case, but it is more complex and it seems reasonable to implement the simpler case first.

@rui314 Thank you as well, I agree with your points and it would be great if the normal linking process becomes faster due to this--that would be even better than what I expected which was merely that the *overall* build time would decrease by removing post-processing.

**Comment by praetorian20** [comment]
Hi @rui314, how does `--separate-debug-info` option compare to `-gsplit-dwarf`? To me, the former looks more convenient because I don't have to use `dwp` to package the DWARF debug info, but are there any other pros/cons to either option?

**Comment by rui314** [comment]
My understanding is that the split-dwarf feature was created based on the observation that linking dwarf info sections took a long time. That assumption no longer holds with mold. So I'd just go with `--separate-debug-info`.

**Comment by lwintermelon** [comment]
@rui314 Does it work with `debuginfod`? I read the commit it seems that it's done by `gnu-debuglink`, what about `.note.gnu.build-id`?

**Comment by rui314** [comment]
If `--separate-debug-info` is given, mold creates two output files -- one is the file specified with `-o` and the other is with the `.dbg` extension. Both files have the same build-id. So I believe debuginfod can associate two files without issues.

**Comment by lwintermelon** [comment]
I'm sure `-gsplit-dwarf` will produce much bigger binary size than expected, see more discussions [here](https://users.rust-lang.org/t/split-debuginfo-packed-produce-much-bigger-binary-than-expected/131473/5).

mold does a great job on this.
