### ISSUE TITLE
SHF_MERGE | SHF_STRINGS are not set

### ISSUE THREAD

**Issue by MaskRay** [rui314/mold#155]
For example, `.debug_str` does not get `SHF_MERGE | SHF_STRINGS`. The flags are probably decorative for many tools but there can be tools picky on the flags.

**Comment by rui314** [comment]
Do you know what tool complains?

**Comment by MaskRay** [comment]
I just speculated that some tools main complain. SHF_MERGE is not too necessarily but it can be an indicator that some input sections have set the bit. `SHF_STRINGS` can be more useful as otherwise tools do not know a random section contains strings.

**Comment by rui314** [comment]
`sh_entsize` shouldn't be 0 if SHF_MERGE is on, but we don't generally know what is an appropriate value for `sh_entsize` for an output section, because we merge input sections with different `sh_entsize` into a single output section. So I decided to revert the above change so that mold simply doesn't set SHF_MERGE in an output file.
