### ISSUE TITLE
-z options not implemented

### ISSUE THREAD

**Issue by dcb314** [rui314/mold#229]
-z options ibt, shstk, cet-report=error do not seem to be implemented.

**Comment by BenBE** [comment]
Which projects did you encounter need these options for building?

**Comment by dcb314** [comment]
frysk, intel-ipsec-mb, libjpeg-turbo so far, but I've only linked projects [0-9a-o]*.

**Comment by BenBE** [comment]
NP. Just asking to ease reproducing those.

**Comment by rui314** [comment]
I'll remove the support of `-z ibt` before making the next release because it depends on Intel MPX. Intel MPX instructions are now deprecated. https://edc.intel.com/content/www/jp/ja/design/ipla/software-development-platforms/client/platforms/alder-lake-desktop/12th-generation-intel-core-processors-datasheet-volume-1-of-2/004/deprecated-technologies/
