### ISSUE TITLE
Support for @rpath and @executable_path

### ISSUE THREAD

**Issue by ob** [rui314/mold#236]
Does `mold` support `@rpath` and `@executable_path`? I'm getting a linker error when I used the flags:

```
$ mold \
... (about 3000 arguments elided) \
-install_name @rpath/VoyagerLibs.framework/VoyagerLibs \
-rpath @executable_path/Frameworks \
...
```
output:
```
mold: cannot open rpath/VoyagerLibs.framework/VoyagerLibs
```

I see from `zld` [this code](https://github.com/michaeleisel/zld/blob/5f37c600a4d2e04fc75997c7a6043f0145b17a3d/ld/src/ld/Options.cpp#L1024) that handles expanding `'@'` in arguments for `@executable_path`, `@loader_path`, and `@rpath`.

This is `mold` built from GitHub:

```
❯ ./mold --version
mold 1.0.1 (70704c7c09b4ff1584ec72347d6b0da3c41aea31; compatible with GNU ld and GNU gold)
```

on macOS Big Sur:

```
❯ sw_vers
ProductName:	macOS
ProductVersion:	11.6.2
BuildVersion:	20G314
```

**Comment by rui314** [comment]
mold for macOS is in the early stage of development, and it lacks lots of features. I'd like to start managing missing features as bugs when it is close to release. It is because, until then, we would naturally have to file lots of bugs for virtually all features. So I'm closing this issue now, but I'll implement the feature soon.

**Comment by BalestraPatrick** [comment]
Hey @rui314! Thanks a lot for all your efforts on this mold so far. This is is still an issue I encountered. Should we reopen this issue? Almost all iOS apps use some kind either `@rpath` or `@executable_path` if they use frameworks.
