### ISSUE TITLE
configure linker detection confused for mold

### ISSUE THREAD

**Issue by marxin** [rui314/mold#290]
I noticed that when inspecting GCC configure script:
https://github.com/gcc-mirror/gcc/blob/6f45deb2aed804b185e7dabd2392bfbe14e9bb57/gcc/configure.ac#L2665-L2669

Unfortunately `mold` prints:
```
$ mold --version
mold 1.0.1 (compatible with GNU ld and GNU gold)
```

So can you please remove the 'GNU ld' and 'GNU gold' strings from version info?
Related to #284.

**Comment by stefson** [comment]
I _think_ this was fixed with https://github.com/rui314/mold/commit/cea6a569afa544826c91fda7ef0f9941f50c9459

**Comment by rui314** [comment]
Yes, please run `git pull` again to sync to HEAD and try again.

We can't remove `GNU ld` from the version string. It's intentionally added to our `--version` string because otherwise lots of `configure` scripts would mis-detect mold that that were extremely old linker that didn't support even shared libraries.

**Comment by marxin** [comment]
> Yes, please run `git pull` again to sync to HEAD and try again. `GNU gold` should be gone.

Great, I can confirm that!

> 
> We can't remove `GNU ld` from the version string. It's intentionally added to our `--version` string because otherwise lots of `configure` scripts would mis-detect mold as an extremely old linker that didn't support even shared libraries.

Oh, makes sense.
