### ISSUE TITLE
Docker build fail for a lot of `undefined reference`

### ISSUE THREAD

**Issue by t0ny-peng** [rui314/mold#317]
Hi Rui314. First thanks for the great work on mold. The performance test is really amazing. 

Btw, I'm trying to use the script you provide to build mold within a container. However it failed for the following message. An example error would be
```
/usr/bin/ld: out/macho/main.o: in function `mold::MappedFile<mold::macho::Context<mold::macho::ARM64> >* mold::macho::find_framework<mold::macho::ARM64>(mold::macho::Context<mold::macho::ARM64>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
```
[output.log](https://github.com/rui314/mold/files/7965539/output.log)
Since I only plan to use `mold` on x86_64, not sure why it still wants to find `ARM64`. Or does `mold` supports cross-platform linking natively(that'd be a nice feature).

Here's my docker and OS version
```
<username>@my-desktop:~/git/mold$ docker --version
Docker version 20.10.11, build dea9396
<username>@my-desktop:~//git/mold$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by rui314** [comment]
If you check out `57f996f80693b3061bb9914bf70285a15cfffecd` (by `git checkout 57f996f80693b3061bb9914bf70285a15cfffecd`) and try again, will it fix your problem?

mold always supports cross-linking, so even if you are building mold on x86-64, it'll build code for ARM64. So that part is not an error.

**Comment by t0ny-peng** [comment]
@rui314 Thanks. I realized that `libc++-dev` needs to be installed in the Docker image. A PR was created to fix that. Please review. Thx

**Comment by rui314** [comment]
It looks like your `ubuntu:20.04` image is different from my `ubuntu:20.04` image. I pulled that image 7 months ago. Since then, I think they made a change to `ubuntu:20.04` image which caused this issue. If that's the case, even if we fix the problem now, it could happen again in the future. We should specify the exact image ID instead of just `20.04`.

If you change `FROM ubuntu:20.04` in `build-static.sh` to `FROM ubuntu@sha256:cf31af331f38d1d7158470e095b132acd126a7180a54f263d386da88eb681d93`, does mold compile?

**Comment by t0ny-peng** [comment]
@rui314 Right. `ubuntu:20.04` is a rolling Docker tag. Hard-coding the image SHA is a good idea. With the specific Docker image you provided, `mold` can be compiled without problem.

**Comment by rui314** [comment]
Thanks, I'll update the build-static script.
