### ISSUE TITLE
mold slowness

### ISSUE THREAD

**Issue by cruisercoder** [rui314/mold#319]
I am seeing slowness for some reason in my mold linking compared to both the default linker and to gold:

default: 10.981s
gold: 2.136s
mold: 7.684s

I remember it being fast before, but I know seem the same results for 0.9.6, 1.0.0, and 1.0.3.   I also see all of the cores (48) being used when mold is active although not always at 100%.  

Separate question: does mold require -Wl,--start-group {{libs}} -Wl,--end-group?  Omitting groups did not make a difference as far as this issue.

**Comment by cruisercoder** [comment]
Correction: mold is much faster.  I had a debug build with symbols on when testing mold.   

default: 10.981s
gold: 3.054s
mold: 0.644s

I discovered some interesting things.  Optimization level 0 (-O0) is a bit faster for compilation (27 vs 30 seconds in one build), but level 1 does dead code elimination which is a big win for the default linker and gold.   It's not as impactful with mold so you can have -O0 on to get both.   I find gold is still useful for global builds until I understand how to tune properly with ninja and mold competing for cores.

-O0

default: 54.155s
gold: 8.947s
mold: 1.935s

-O1 (includes dead code elimination)

default 10.525s
gold: 3.003s
mold: 1.536s

**Comment by rui314** [comment]
What is your program size? If mold takes 0.644s to produce a 600 MiB executable, that's not an odd number. For a 100 MiB executable, for example, that looks a bit too slow.

**Comment by cruisercoder** [comment]
It's 199M, so it might match what you are expecting.

Do I need --start-goup/--end-group with either mold or gold?

**Comment by rui314** [comment]
gold interprets --start-group/--end-group while mold ignores them. It's documented in mold's man page. https://rui314.github.io/mold.html#Archive_symbol_resolution

**Comment by rui314** [comment]
--start-group/--end-group directives instruct the linker to visiting archive files within --start-group and --end-group until no new symbols can be resolved. Since mold can simply "go back" in the command line arguments, we can ignore them.

**Comment by BenBE** [comment]
Couldn't this (hypothetically) cause a difference when a certain symbol is defined multiple times and ignoring those groups causes the symbol to be used from a file outside that group?

**Comment by rui314** [comment]
Yes it can. I was worried about that when we were creating lld when I was working at Google, because GNU ld's naming resolution algorithm is the way how Unix had been working for 40 years. But to our surprise, almost all programs turned out to work just fine with a different name resolution algorithm. I think the reason is because, if your program changes behavior depending on the name resolution algorithm, your program is probably too fragile from the beginning as it's likely to contain two different definitions of the same symbol in different archive files. So, people usually avoid doing that, and if they do, they do it explicitly (i.e. overriding libc functions with your own library by prepending `-lyour-library` to the command line.)
