### ISSUE TITLE
-s does not work

### ISSUE THREAD

**Issue by trcrsired** [rui314/mold#359]
gcc and clang have the toggle -s, but mold does not invoke it to strip binary. Can we add this?

Also, the binary generated by mold is larger than gold even after stripping. Why?

-rwxrwxr-x 1 cqwrteur cqwrteur  14864 Feb 22 19:12 construct_fstream_from_syscall_gold
-rwxrwxr-x 1 cqwrteur cqwrteur  23200 Feb 22 19:12 construct_fstream_from_syscall_mold

**Comment by rui314** [comment]
It looks like `-s` is working fine with mold. If I add `-s` to the final link line, mold generates an executable without .symtab and .debug_ sections.

As to the difference after `strip`, I believe that's because mold page-aligns more than gold does. Can you run `readelf --sections` on both executables to see what's inside?
