### ISSUE TITLE
Undefined symbol `___tls_get_addr` when linking statically for i686

### ISSUE THREAD

**Issue by sicherha** [rui314/mold#388]
Minimal test case (derived from `test/elf/exception.sh`):
```sh
#!/bin/sh

set -e

cat <<EOF | c++ -xc++ - -m32 -B. -o exe -static
int main() {
  try {
    throw 0;
  } catch (int x) {
    return x;
  }
  return 1;
}
EOF
```

Output:
```
mold: error: undefined symbol: /usr/lib/gcc/x86_64-redhat-linux/11/32/libstdc++.a(eh_globals.o): ___tls_get_addr
mold: error: undefined symbol: /usr/lib/gcc/x86_64-redhat-linux/11/32/libstdc++.a(eh_globals.o): ___tls_get_addr
collect2: error: ld returned 1 exit status
```
I'm on Fedora 35 with GCC 11.2.1 and glibc 2.34.

**Comment by rui314** [comment]
`___tls_get_addr` is referenced by `eh_globals.o` in `libstdc++.a`. Usually, the definition of the symbol is provided by `libc.so`, but since you are doing static linking, no one defines the symbol.

The reason why we don't see the `undefined symbol` error on x86-64 is because we relax TLS relocations. By doing that, we skip the relocation referring that `__tls_get_addr` symbol, so we don't see the `undefiend symbol` error.

Therefore, the correct way to fix this is to implement TLS relocation relaxation for i386.
