### ISSUE TITLE
fail to build xwayland 22.1.1 on x86_64 with mold 1.1.1, success with gold (inside docker container)

### ISSUE THREAD

**Issue by satmandu** [rui314/mold#410]
Error message:
```
[418/428] Linking target test/damage/damage-primitives
FAILED: test/damage/damage-primitives 
cc  -o test/damage/damage-primitives test/damage/damage-primitives.p/primitives.c.o -flto -Wl,--no-undefined -Wl,-O1 -pie -fvisibility=hidden -flto -O2 -pipe -flto -ffat-lto-objects -fPIC -fuse-ld=mold -Wl,--start-group /usr/local/lib64/libxcb.so /usr/local/lib64/libxcb-damage.so -Wl,--end-group
terminate called after throwing an instance of 'std::runtime_error'
  what():  pthread_create has failed: Resource temporarily unavailable
collect2: fatal error: ld terminated with signal 6 [Aborted]
compilation terminated.
```

Failure:
[xwayland-22.1.1-x86_64.mold.log](https://github.com/rui314/mold/files/8390085/xwayland-22.1.1-x86_64.mold.log)

Success:
[xwayland-22.1.1-x86_64.log](https://github.com/rui314/mold/files/8390089/xwayland-22.1.1-x86_64.log)

**Comment by rui314** [comment]
It failed because "Resource temporarily unavailable". Does your machine have enough RAM?

**Comment by satmandu** [comment]
The machine has 48Gb of ram.

**Comment by rui314** [comment]
There might be some other resources that are not plenty enough. Does this fail if you run ninja with `-j1`?

**Comment by rui314** [comment]
I saw the same error yesterday when running LTO tests while other heavy jobs were running in background, so this seems real. It's not easy to reproduce though.

**Comment by ishitatsuyuki** [comment]
From Googling the error — this issue might be caused by the `TasksMax` limit which effective limits the amount of threads all containers can have in total.

https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel

mold uses TBB so by default it spawns as much threads as the cores available on the machine. If you have many cores with a low `TasksMax` limit, I can imagine this exploding pretty soon when multiple ld invocations are running in parallel.

I'd suggest checking the `Tasks` statistic during linking per the answer in the SE question above. If that's indeed the case, the workaround would be increasing the `TasksMax` limit, and if we want to tackle with that on mold side, we could add an option to limit parallelism.

**Comment by rui314** [comment]
It looks like `pthread_create` can spuriously fail even if we have enough resources to create a thread. Go for example has a logic to workaround that issue: https://go-review.googlesource.com/c/go/+/33894/

I implemented the same logic in mold in the above commit.

@satmandu Please rebuild mold and try again to see if this workaround works for you. Note that you need to build mold _without_ `SYSTEM_TBB` makefile flag if you passed that flag before, as my patch is against a vendored copy of OneTBB.

**Comment by rui314** [comment]
I created a PR to the upstream: https://github.com/oneapi-src/oneTBB/pull/824

**Comment by satmandu** [comment]
I can confirm that using a build of mold  from this commit allows me to build xwayland.
