### ISSUE TITLE
RV64: Implement TLS relaxation

### ISSUE THREAD

**Issue by rui314** [rui314/mold#461]
mold currently doesn't relax any TLS relocations at all. We should implement GD → LE and LD → LE relaxations just like we did to x86-64.

**Comment by ksco** [comment]
Hi Rui,

I would like to implement this but it may take some time as I am not familiar with the ELF TLS model.

**Comment by rui314** [comment]
Sure. I'll assign this bug to you to avoid duplicate effort. Feel free to ask any questions.

**Comment by ksco** [comment]
Firstly, I'm trying to open all the `tls-*` tests for RV32 and RV64 and everything works fine except for one issue.

In [tls-gd.sh](https://github.com/rui314/mold/blob/main/test/elf/tls-gd.sh), in the end, we are trying to statically link the three PIC object files together. In this very case, the output becomes 0 2 0 0 0 0 instead of the expected 1 2 3 4 5 6, I haven't found the reason yet.

https://github.com/ksco/mold/commit/06a2daa19df8c406a2dd1eba52fdbc6523c8ad52#diff-8d8a35fafde296bbdfcf817940e5559dc0fb2a1bc4aaea5822870253cdbaac74R68

**Comment by rui314** [comment]
TLS is super tricky. I don't know what's wrong, let me take a look.

**Comment by rui314** [comment]
I fixed the issue in the above commit.

**Comment by ksco** [comment]
That's amazing!

**Comment by ksco** [comment]
I think this is done since we already handled the Thread-pointer Relaxation, right?

**Comment by rui314** [comment]
By TLS relaxation, I meant conversion of General Dynamic → Local Exec and Local Dynamic → Local Exec, and not the RISC-V-specific %tp optimization. But I found that the RISC-V psABI lacks a mechanism to allow GD → LD (https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/308), so maybe this is infeasible. It's a spec bug, though.

**Comment by ksco** [comment]
Oh, seems they're gonna add this mechanism after spec 1.0 is released, so I think I'll just wait till that happens.

**Comment by rui314** [comment]
TLSDESC for RISC-V has now been ratified, and we've implement it to mold. I think we can close this issue now.
