### ISSUE TITLE
RFE: move to meson build framework

### ISSUE THREAD

**Issue by kloczek** [rui314/mold#547]
Would you welcome PR with move from custom Makefile files to meson? 🤔

**Comment by Alcaro** [comment]
We added cmake support a while ago, #49.

Then we removed it, e4e85353455675d8f46c3136fe121a011355f34b.

My guess is that Meson would meet the same fate, but maybe things have changed since last year. Only Rui knows.

**Comment by kloczek** [comment]
Meson is way better because it provides some interface to the packaging layer (look on `meson introspect`).
With cmake attempt it would be easier to prepare meson files 😋 
Other thing is that as long as current custom make files are working any other build framework can exist on side of those files until at some point decision about stop using those files will be made.

**Comment by kloczek** [comment]
So what was the exact problem which caused remove cmake support? 🤔

**Comment by sicherha** [comment]
> So what was the exact problem which caused remove cmake support? thinking

From the commit message of e4e85353455675d8f46c3136fe121a011355f34b:
> I was experimenting with cmake to see if it is useful for mold,
> but it looks like using cmake doesn't make much sense for us.
> So I'm undoing all changes that I did for cmake.
>
> cmake is definitely better than autoconf, and it is also useful
> if your program is cross-platform. However, neither of the benefits
> don't apply to mold; mold doesn't need a complex feature detection,
> and it currently supports only ELF-based Unix-like systems.
>
> I think Makefile is a lingua-franca, while CMakeLists.txt isn't.
> The good ol' Makefile works just fine for mold.
>
> In the future, mold might become a cross-platform product, and if
> that happens, we might want to re-introduce cmake.

**Comment by kloczek** [comment]
There are some useful buts which are coming with meson:
- OOTB coverity
- declarative description of the build (cmake is more like functional)
- fully transparent for env variables like CC, CXX, RANLIB, LD, AR, CFLAGS. CXXFLAGS, LDFLAGS
- better interface for all people like me (packagers)

If you care about fact how often mold is and could be used you need to think, a bit broader and agree that not only you are using to build mold binaries. With that accepted should come acceptance that usefulness may have a bit broader definition than yours and/or in some way sometimes even a bit orthogonal to your private goals. With that will come a lot of help (sooner or later).

**Comment by kloczek** [comment]
And look on doe example zstd.
It provides now custom Makefile file, meson and cmake support (because maintainer was not sure which one would be the best).
However now if you will look across all distribution you may find that almost always meson is used.

**Comment by rui314** [comment]
I think the biggest reason why I want to stick with `make` is because I'm most familiar with that build system and not that much with other ones. I'm still writing most of the code for this project, and it is important to use the tool that "majority" of the developers have already understand well to keep them productive. That doesn't mean that I don't want to learn new tools, but at the moment, I want to focus on improving the mold linker itself rather than learning build systems and choose the best one. That's also the thing people who are watching the progress of this project are expect from me.

zstd is as a comparison too sophisticated. That's a library which is expected to be build in various environments and sometimes as a part of other large program. That's backed by Facebook which obviously has much more resources than me to maintain different build systems. As another example, take a look at `git`. It's being used everywhere, but it only has a Makefile.

So `make` may not be an ideal tool, but we don't have a strong reason to replace it at the moment.

**Comment by ishitatsuyuki** [comment]
meson is a great tool, but the 200-line Makefile has also been serving mold's use case well enough.

If you're proposing to migrate to another build system, I think here are some required features from the current Makefile system that you could look into:

- Running tests with ASan/TSan, and also toggling the mimalloc allocator which conflicts with the sanitizer tracking.
- Running our custom shell script-based tests, with differing sanitizer options and target configs.
- Ensure all the feature/workaround testing in the current Makefile are carried over.

**Comment by eli-schwartz** [comment]
While in my biased opinion I'd definitely recommend meson over cmake... the rationale for sticking with a Makefile seems quite good?

It's not an indictment on any particular build system, merely a statement that the project isn't currently complicated enough to need a build system at all. The hardest thing is always getting cross-platform stuff to work. If you don't need that, you don't need that.

That being said:

> * Running tests with ASan/TSan

This works so well that it is provided out of the box in Meson, there's a builtin option for it. :)

Linking to a third-party library is not a built-in option (although Meson does have nice handling for toggling on/off the use of system/vendored libraries).


> * OOTB coverity
> 
> * declarative description of the build (cmake is more like functional)
> 
> * fully transparent for env variables like CC, CXX, RANLIB, LD, AR, CFLAGS. CXXFLAGS, LDFLAGS
> 
> * better interface for all people like me (packagers)

Meson is nice for a bunch of these, but as far as the env variables go, the current Makefile already respects CC, CXX and LDFLAGS, doesn't use RANLIB, LD or AR, and while it doesn't properly support CFLAGS or CXXFLAGS, that can be trivially fixed:
- the current Makefile overwrites the environment variables with `-O2` but can be worked around by passing it as an explicit argument to Make
- the correct standard solution is to use `?=` instead of `=`

> It provides now custom Makefile file, meson and cmake support (because maintainer was not sure which one would be the best).

I don't think zstd is the best comparison, because the zstd developers have declared only Makefiles are official, and all other build systems are in a separate directory "out of the way"...

They mainly exist, to my knowledge, because they are useful for library support. Namely, that you can then integrate zstd into your own project as a submodule and build it via meson subproject wrap fallback / cmake `add_subdirectory()` and thereby link to libzstd-the-library and still have a unified build system.

Obviously this concern does not apply to an executable utility. So I would not recommend supporting multiple build systems at all, with the common exception of "you may wish to support exactly two build systems ***temporarily*** during a transition phase from one to the other".

**Comment by kloczek** [comment]
Thank you @eli-schwartz. You been faster to cover ALL topics 😃 

As I wrote using zstd way would allow to extend use cases of the mold outside of the strict maintainer goals without trashing them 😋 
So those build frameworks could exist in git tree together without collision.

Issue is that in current state of the operating system distribution all software components integrated in such higher level of objects needs to be easy pluggable into distribution automations. cmake here is a bit behind (and I have big doubts is it will be possible to do with use functional description but that is completely different topic) but meson already started to provide such interface.
In case of Makefile files it would be literally impossible to provide such interface. Why? Because such interface is completely independent from what is in build automation framework description, With fully declarative discretion such interface do not force add any additional lines of code in meson.build files. Avg Joe mold "consumer" building it he/she may be even completely unaware that such interface meson provides 😋 
With non-zero size of the community of people having business to use meson or cmake you don't need to care about that parts to much.
Because mold has IMO great potential I don't thing so that it will be to much noise for you as maintainer to care about those bits to much 😃

**Comment by rui314** [comment]
@kloczek I don't know if I understand all the points you mentioned correctly, but the point I wanted to make is that I as the lead developer of this project need to understand the build system of this project very well. Currently, `make` is the tool of our choice, and I'm fairly satisfied with it. It doesn't also have a showstopper issue for those who create binary packages for Linux distros. So I want to stick with it.

**Comment by kloczek** [comment]
> I don't think zstd is the best comparison, because the zstd developers have declared only Makefiles are official, and all other build systems are in a separate directory "out of the way"...

They have support for meson, cmake and Makefile files. As far as I've checked few distros almost all choose to use meson.
I found some time ago small issue and it was solved by author oft the meson support almost instantly.
IMO all three are treated equally.
I understand that use cmake can make sense as well if cmake is used above basic packages (the same trick is possible with meson).

IMO it would be rally nice to give chance to add (and not replace existing Makefile files) meson support.

Issue is as well that exact project is not only for exact project maintainer and some people have some use cases with integrating many projects like mold into something bigger with or without package management software layer.
As I understand point of view of the maintainer I would like to see as well give some ground (only a bit) for those who are building and packaging software like mold.
I'm sure that we can meet somewhere in the middle 😋

**Comment by vtorri** [comment]
Makefile will be more complicated when Windows port will be done, and would be usable on Windows only with tools like MSYS2.
Advantages of meson (imo)

 * very fast (a bit faster than cmake, especially on Windows platform)
 * nicer syntax than cmake (close to python)
 * options are clearly readable in a separate file
 * wrapdb features to manage dependencies
 * create dist tarballs integrated in meson
:

**Comment by Tachi107** [comment]
The CMake build system was merged a few days ago, see #571.

I guess that Meson as the main build system won't happen :/

**Comment by kloczek** [comment]
😞

**Comment by kloczek** [comment]
Looks like that cmake support is as bad as those custom Makefile files 😞

**Comment by Tachi107** [comment]
There's no need to hate on CMake. If you're encountering issues with building Mold with it, report them as a separate ticket. As far as I understand CMake support is still incomplete/experimental.

**Comment by eli-schwartz** [comment]
> That doesn't mean that I don't want to learn new tools, but at the moment, I want to focus on improving the mold linker itself rather than learning build systems and choosing the best one.

If @rui314 is now open to dealing with non-Makefile build systems (particularly with a mind to Windows support) then I assume that means Meson is now a viable candidate option for reasons people have suggested above.

I guess if someone really wants to see mold built with Meson, the next step is to propose a PR that adds one. The project maintainer can then compare and contrast the two, experiment with using them, and decide on one or the other.

It's a good time for that sort of experiment, I guess, since AFAIK the project maintainer doesn't have a strong preference for cmake, and the cmake support that is there, is "still incomplete/experimental".

**Comment by rui314** [comment]
I think CMake was a reasonable choice. I don't want to make mold to depend on too many external tools to build. CMake can be installed from the Visual Studio Installer, so it seems like the best choice for us. On Windows, users won't have to install anything other than Visual Studio to build mold.

**Comment by Tachi107** [comment]
I don't think a user compiling Mold from source will have issues installing a .msi package, but yeah you've got a point nonetheless :)

**Comment by rui314** [comment]
I'm not a person who just build my own program but also a person who build other people's programs a lot. I've been receiving many bug reports with mold for programs that I'm not familiar with, and I also found many issues in mold by compiling lots of Gentoo packages myself. To debug these issues, I have to build them first. In that situation, I found it's so much easier to build a program with a conservative build system than those I'm not familiar with. So I personally appreciate projects with traditional build systems. It doesn't necessarily mean that newer build systems are bad; I just want to stick with Make or CMake as long as they work well for us.

**Comment by eli-schwartz** [comment]
> I don't want to make mold to depend on too many external tools to build.

Note that Meson is a pip install away and is only 1mb. On:
- Windows, python is a very common tool to have on developer systems
- Unix, python is nearly always installed because various parts of the OS depend on it
 
https://sr.ht/~lattis/muon/ is a 2.5mb (compressed) statically linked single-file program that implements the Meson spec, at least on Unix, and even comes with ninja built in. (There is someone working to add Windows support, but obviously, do not rely on something that doesn't exist today.)

CMake is anywhere from 40mb (Windows) to 45mb (Linux) to 70mb (macOS), and users trying to compile via mingw will not have Visual Studio installed.

(I would not call meson particularly new -- it's a decade old.)

...

That being said, of course the most important thing is what works best for you, the developer. But I thought you said you weren't familiar with either Meson or CMake. :p

**Comment by kloczek** [comment]
> There's no need to hate on CMake. If you're encountering issues with building Mold with it, report them as a separate ticket. As far as I understand CMake support is still incomplete/experimental.

What I wrote has nothing to do with hate.
Here is short list of design issues:
- hardcofig optimisation flags
- hardcoging linker flags
- preffering use submodules over pure pkgconfig detection

In other words it has nothing to do with cmake per se but with exact design/implementation.
On top of that it is siome `tbb` detection issue
```console
+ /usr/bin/cmake -B x86_64-redhat-linux-gnu -D BUILD_SHARED_LIBS=ON -D CMAKE_AR=/usr/bin/gcc-ar -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_C_FLAGS_RELEASE=-DNDEBUG -D CMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D CMAKE_Fortran_FLAGS_RELEASE=-DNDEBUG -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_NM=/usr/bin/gcc-nm -D CMAKE_RANLIB=/usr/bin/gcc-ranlib -D CMAKE_VERBOSE_MAKEFILE=ON -D INCLUDE_INSTALL_DIR=/usr/include -D LIB_INSTALL_DIR=/usr/lib64 -D LIB_SUFFIX=64 -D SHARE_INSTALL_PREFIX=/usr/share -D SYSCONF_INSTALL_DIR=/etc -S . -D MI_BUILD_OBJECT=ON -D MI_BUILD_SHARED=ON -D MI_BUILD_STATIC=OFF -D MI_BUILD_TESTS=ON -D MI_CHECK_FULL=OFF -D MI_DEBUG_FULL=OFF -D MOLD_USE_SYSTEM_MIMALLOC=ON -D MOLD_USE_SYSTEM_TBB=OFF -D TBB_BUILD=OFF
-- The C compiler identification is GNU 12.1.1
-- The CXX compiler identification is GNU 12.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXX_SUPPORTS_FUSE_MOLD
-- Performing Test CXX_SUPPORTS_FUSE_MOLD - Failed
CMake Warning at third-party/tbb/CMakeLists.txt:114 (message):
  You are building oneTBB as a static library.  This is highly discouraged
  and such configuration is not supported.  Consider building a dynamic
  library to avoid unforeseen issues.


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for one of the modules 'hwloc'
-- HWLOC target HWLOC::hwloc_1_11 doesn't exist. The tbbbind target cannot be created
-- HWLOC target HWLOC::hwloc_2 doesn't exist. The tbbbind_2_0 target cannot be created
-- HWLOC target HWLOC::hwloc_2_5 doesn't exist. The tbbbind_2_5 target cannot be created
-- Looking for getcontext
-- Looking for getcontext - found
CMake Error at CMakeLists.txt:108 (target_compile_definitions):
  Cannot specify compile definitions for target "tbb" which is not built by
  this project.
Call Stack (most recent call first):
  CMakeLists.txt:112 (mold_add_tbb)


-- Looking for pow in m
-- Looking for pow in m - found
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "3.0.5") found components: Crypto
-- Found Python3: /usr/bin/python3.8 (found version "3.8.13") found components: Interpreter
-- Configuring incomplete, errors occurred!
See also "/home/tkloczko/rpmbuild/BUILD/mold-1.4.1/x86_64-redhat-linux-gnu/CMakeFiles/CMakeOutput.log".
See also "/home/tkloczko/rpmbuild/BUILD/mold-1.4.1/x86_64-redhat-linux-gnu/CMakeFiles/CMakeError.log".
```

**Comment by rui314** [comment]
We have made a decision to go with CMake, so let me close this issue.
