### ISSUE TITLE
[feature request] add CI for compilation with MSYS2 + mingw-w64

### ISSUE THREAD

**Issue by vtorri** [rui314/mold#615]
as an example:

https://github.com/vtorri/libdvi/blob/master/.github/workflows/ci_msys2.yml

Note: mimalloc and tbb are available with MSYS2. For x64_64 host

pacman -S mingw-w64-x86_64-mimalloc mingw-w64-x86_64-tbb

**Comment by rui314** [comment]
Could you tell me a little bit more about your motivation to support mingw? My motivation is to make mold work on Windows however it is, so if mold does compile on Windows with MSVC, I'm fine with that. Once our mold/Windows implementation is done, you'll be able to use mold with mingw, but that doesn't necessarily mean that you want to build mold with mingw too.

**Comment by vtorri** [comment]
with MSYS2, you have a POSIX-like environment, with the package manager similar to the Archlinux one. So it is easy to install them. Also, it will be possible to package mold for msys2 and install it with pacman.

Normally, if it compiles for MSVC, it should compile for mingw (the contrary is not necessarly true).

Also, you'll be able to benchmark binaires produced with msvc and gcc on Windows, and see which one is faster. Usually, gcc on Windows produces binaries which are faster than those compiled with MSVC.

**Comment by rui314** [comment]
These days MSVC is shipped with clang, and we use clang to build mold. MSVC can't actually compile mold due to the silly 128-level block nesting depth limitation (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1061). I believe clang's output is as good as gcc's.

As to dependencies, we bundle all dependent libraries in our repo, so it's easy to build. MSVC comes with cmake and clang, so you don't need anything other than MSVC to build mold on Windows.
