### ISSUE TITLE
error with mingw and clang

### ISSUE THREAD

**Issue by 3rav** [rui314/mold#622]
After switching form gcc to clang, by:

```
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
```

```
==> Starting build()...
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
```

errors occurs:

```
[77/89] Building CXX object CMakeFiles/mold.dir/main.cc.obj
FAILED: CMakeFiles/mold.dir/main.cc.obj
C:\msys64\mingw64\bin\clang++.exe -DNOGDI -DNOMINMAX -DMOLD_VERSION=\"1.4.0\" -IC:/msys64/usr/local/pkg_mold/src/mold-main/third-party/mimalloc/include -IC:/msys64/usr/local/pkg_mold/src/mold-main/third-party/tbb/src/tbb/../../include -march=x86-64 -mtune=generic -O2 -pipe -O2 -g -DNDEBUG -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -std=gnu++20 -MD -MT CMakeFiles/mold.dir/main.cc.obj -MF CMakeFiles\mold.dir\main.cc.obj.d -o CMakeFiles/mold.dir/main.cc.obj -c C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:47:58: error: expected ')'
static LONG WINAPI vectored_handler(_EXCEPTION_POINTERS *exception_info) {
                                                         ^
C:/msys64/mingw64/include/excpt.h:53:54: note: expanded from macro 'exception_info'
#define exception_info (struct _EXCEPTION_POINTERS *)_exception_info
                                                     ^
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:47:36: note: to match this '('
static LONG WINAPI vectored_handler(_EXCEPTION_POINTERS *exception_info) {
                                   ^
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:51:54: error: member reference base type 'void *() __attribute__((cdecl))' is not a structure or union
  PEXCEPTION_RECORD exception_record = exception_info->ExceptionRecord;
                                       ~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:51:21: error: cannot initialize a variable of type 'PEXCEPTION_RECORD' (aka '_EXCEPTION_RECORD *') with an rvalue of type 'struct _EXCEPTION_POINTERS *'
  PEXCEPTION_RECORD exception_record = exception_info->ExceptionRecord;
                    ^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/usr/local/pkg_mold/src/mold-main/main.cc:66:3: error: no matching function for call to 'AddVectoredExceptionHandler'
  AddVectoredExceptionHandler(0, vectored_handler);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/mingw64/include/errhandlingapi.h:25:29: note: candidate function not viable: no known conversion from 'LONG (_EXCEPTION_POINTERS *(*)(struct _EXCEPTION_POINTERS *))' (aka 'long (_EXCEPTION_POINTERS *(*)(struct _EXCEPTION_POINTERS *))') to 'PVECTORED_EXCEPTION_HANDLER' (aka 'long (*)(_EXCEPTION_POINTERS *)') for 2nd argument
    WINBASEAPI PVOID WINAPI AddVectoredExceptionHandler (ULONG First, PVECTORED_EXCEPTION_HANDLER Handler);
                            ^
4 errors generated.
[78/89] Building CXX object CMakeFiles/mold.dir/macho/tapi.cc.obj
```

**Comment by Alcaro** [comment]
Relevant part of the header:
```c
#define GetExceptionCode _exception_code
#define exception_code _exception_code
#define GetExceptionInformation (struct _EXCEPTION_POINTERS *)_exception_info
#define exception_info (struct _EXCEPTION_POINTERS *)_exception_info
#define AbnormalTermination _abnormal_termination
#define abnormal_termination _abnormal_termination

  unsigned long __cdecl _exception_code(void);
  void *__cdecl _exception_info(void);
  int __cdecl _abnormal_termination(void);
```
In my opinion, that's a mingw bug. It should either declare _exception_info with the correct return type, or put the cast in an inline function instead of a macro. Or discard exception_info completely, no need for both that and GetExceptionInformation.

A few workarounds for compiler quirks is fine (https://github.com/rui314/mold/commit/73ee17337cd89ffd761f16217930e288dc9c947c, https://github.com/rui314/mold/issues/308), but if the compiler is too weird, the pragmatic solution is to deem it unsupported (https://github.com/rui314/mold/commit/4050f5241f9af756917577be6c88b76db7e59a48, https://github.com/rui314/mold/issues/603#issuecomment-1209147022).

Rui's choice where the point of 'too weird' lies, of course. And even if deemed unsuitable, it's probably wise to detect mingw (and Termux and whatever else) and stick a #error "use clang-cl instead" in some prominent place (probably some header included everywhere, so some well-meaning mingw user doesn't see only half of the errors and submit PRs for them).

**Comment by rui314** [comment]
So the current situation is this:

- We use clang-cl which comes with Visual Studio 2022 Community Edition that is available free of charge.
- Only clang-cl can build mold on Windows. Even MSVC's native cl.exe can't build mold.

The question we are discussing here is that whether we want to support mingw or not.

My opinion is given this situation this: I don't want to pursue mingw compatibility from the very beginning of the project. It may or may not compile with other compilers, but I want to focus on writing code that compiles with MSVC's clang-cl.

If you want to build mold, please install MSVC Community Edition with clang-cl and cmake extra packages (which you can install from Visual Studio Installer.)

This policy may change when our product becomes more mature. But in the early stage of development, I want to focus on mold/Windows itself rather than its cross-toolchain portability.

**Comment by vtorri** [comment]
ok, I stop working on this

**Comment by 3rav** [comment]
After this modification:
1. Add to CMakeLists.txt (https://github.com/rui314/mold/pull/618)
```
 target_compile_features(mold PRIVATE cxx_std_20)
 target_link_libraries(mold PRIVATE ${CMAKE_DL_LIBS})
 
+if(WIN32)
+    target_compile_definitions(mold PRIVATE _WIN32_WINNT=0x0A00)
+endif()
+
 if(NOT "${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}" STREQUAL "MSVC")
   target_compile_options(mold PRIVATE
     -fno-exceptions
```
2. Commenting lines from 84 to 136 main.cc (version 1.9.0), compilation runs almost to the end 268/269
```
/*
#ifdef _WIN32

static LONG WINAPI vectored_handler(_EXCEPTION_POINTERS, *exception_info) {
  static std::mutex mu;
  std::scoped_lock lock{mu};
```
to
```
  sigaction(SIGBUS, &action, NULL);
}

#endif
*/
```

**Comment by 3rav** [comment]
Hi @rui314
Error related to `exception_info` has been fixed (modification of excpt.h file, https://sourceforge.net/p/mingw-w64/mingw-w64/ci/4359b3570a717d20dcb4251f5b5e94459e1a64ac/), this caused mold to compile successfully for both gcc and clang, requiring only three modifications:

1. CMakeLists.txt, from: https://github.com/rui314/mold/pull/618/files
```
if(WIN32)
    target_compile_definitions(mold PRIVATE _WIN32_WINNT=0x0A00)
endif()
```
2. CMakeLists.txt, from: https://github.com/msys2/MINGW-packages/issues/14957#issuecomment-1374392914
```
 @@ -204,6 +208,7 @@
   endif()
 
   target_compile_definitions(mold PRIVATE NOGDI NOMINMAX)
+  target_link_libraries(mold PRIVATE stdc++ bcrypt)
 else()
   include(CheckLibraryExists)
   check_library_exists(m pow "" LIBM_FOUND)
```
3. CMakeLists.txt, delete symbolic link:
```
@@ -432,8 +437,7 @@
       get_filename_component(NEW_DIR \${NEW_ABS} DIRECTORY)
       file(RELATIVE_PATH OLD_REL \${NEW_DIR} \${OLD_ABS})
       message(STATUS \"Installing symlink: \$ENV{DESTDIR}\${NEW_ABS} -> \${OLD_REL}\")
-      file(MAKE_DIRECTORY \$ENV{DESTDIR}\${NEW_DIR})
-      file(CREATE_LINK \${OLD_REL} \$ENV{DESTDIR}\${NEW_ABS} SYMBOLIC)")
+      file(MAKE_DIRECTORY \$ENV{DESTDIR}\${NEW_DIR})")
   endfunction()
```

After these modifications, the compilation runs successfully for both GNU gcc and clang in the msys2/mningw environment.
