### ISSUE TITLE
Build without Python

### ISSUE THREAD

**Issue by equal-l2** [rui314/mold#636]
Mold 1.4.1 introduced `update-git-hash.py` and now it requires Python to build.
Can we build mold without Python as before?

Context: https://github.com/Homebrew/homebrew-core/pull/108346

**Comment by ZhongRuoyu** [comment]
I also faced an issue while building mold 1.4.1 on Ubuntu 16.04 (yeah, although it's quite outdated). The latest `python3` available in Ubuntu 16.04's package archive is Python 3.5, but `update-git-hash.py` uses [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings), which was introduced in Python 3.6. Maybe it would be nice to drop this not-so-necessary build dependency?

Maybe we can translate that Python script to a shell script, I suppose? Due to this issue I've actually already done the translation work. If @rui314 thinks this is feasible, I think I can open a PR.

**Comment by MarcusJohnson91** [comment]
My project FoundationIO has a cmake file that reads the githash, take a look at that to fix this @rui314

**Comment by rui314** [comment]
The Python script was rewritten in CMake. You can see the source code here: https://github.com/rui314/mold/blob/main/update-git-hash.cmake

**Comment by carlocab** [comment]
@ZhongRuoyu has a rewrite of the `update-git-hash` script in `bash` at https://github.com/ZhongRuoyu/mold/commit/41793ca3588df983e4fefc3d0ff12f46f5f433cb. Not sure if they were planning to contribute it, but it would be nice to use `bash` instead.

At Homebrew, we build from a tarball with no Git information, so the CMake `update-git-hash` still means we need a `cmake` installation in order to write a file that only says
```cxx
#include <string>
namespace mold {
std::string mold_git_hash = "";
}
```
which seems rather wasteful.

**Comment by rui314** [comment]
@carlocab
Makefile is going to be deprecated. I didn't recommend switching over to CMake when I released 1.4.1 because I wasn't sure if the CMake would work for packagers. But if you find that CMake just works for you, please go ahead and start using it.

**Comment by MarcusJohnson91** [comment]
Your build bots don’t include cmake????

**Comment by Alcaro** [comment]
Not by default, no. To ensure prior compiles don't break anything, every build starts with configuring a new buildbot, which initially contains absolutely nothing, not even a C compiler.

It is, of course, easy to include new tools (like g++, cmake and Python), but each included tool costs another bit of resources, so it's natural to want to keep the list of included tools as small as possible.

But in this case, 'as small as possible' includes cmake.

**Comment by carlocab** [comment]
> Your build bots don’t include cmake????

A package manager's build bot should be as bare as possible, or else you might end up with a package definition that works on the build bot but not on a user's machine. This means that CMake is not installed unless a package requests it, but that occurs only when (and on each time) a package that requests CMake is built.

This introduces some overhead when setting up and tearing down the build bot. But growing the dependency tree also means that testing new versions of packages (in this case CMake) also takes just a little bit longer than before (and this adds up to multiple-day testing runs in the case of some packages).

**Comment by carlocab** [comment]
> But if you find that CMake just works for you, please go ahead and start using it.

Switching the Homebrew build to CMake at Homebrew/homebrew-core#108559. I found I needed 9c61fc648d52d93ca2c04241c202ebfa8a017b0c, but I don't mind carrying the patch until it comes out in the next release.

Thanks, @rui314.
