### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by nico-abram** [rui314/mold#8]
I apologize if you already have a license and I missed it (I couldn't find one)

**Comment by rui314** [comment]
I haven't made my mind yet as to the license of this software. I want to make money from this software if I can, but at the same time I want this to be used as widely as possible. Ideally, if I can find a sponsor who will "purchase" this entire program (not a copy of it) and release it under the MIT license or something, it would be great. But if I release this under the MIT license from the beginning, no one has to do that in the first place. So, this is not an easy problem for me.

At this moment, I'm not too worried about not choosing a license. License matters when a program becomes something that people want to use, and IMO mold hasn't reached that point. This is still just my hobby, experimental project.

**Comment by xyproto** [comment]
I can't package `mold` for Arch Linux unless it has a license.

**Comment by rui314** [comment]
Beside the license issue, I believe it is too early to create a package for mold. It's too experimental.

**Comment by tux3** [comment]
A note to any hypothetical person in the business of pedantically following copyright law: according to [GitHub's choosealicense.com](https://choosealicense.com/no-permission/) and [this StackOverflow Q/A](https://opensource.stackexchange.com/questions/1720), the GitHub ToS only guarantee that the code can be viewed publicly, and forked _on GitHub_. 

In theory mondane things like making a local git clone or running the program are not allowed without acquiring a personal license.

Of course there are disturbing reports that international copyright law silliness rarely stops individual users, but I couldn't possibly confirm or deny that =)

**Comment by xyproto** [comment]
In addition to this, Linux distros need to be careful not to become Pirate Linux distros. A license file helps a lot.

**Comment by ssokolow** [comment]
Just a data point here. I'm very particular about using only free/libre tooling (ie. tooling under licenses that meet criteria like the Debian Free Software Guidelines) for my modern projects, so I'm waiting to see what license this winds up under before touching the code at all.

(I say "my modern projects" because I made an exception for Open Watcom C/C++'s "too copyleft" license for DOS hobby projects and I'm still split on whether to do my Windows 3.1 retro-hobby programming exclusively in Open Watcom C/C++ or to use my New Old Stock copy of Borland Delphi 1.x for rapid prototyping and risk not having time to rewrite in C when I release the source for others hobbyists to hack on.)

**Comment by rui314** [comment]
Folks, I just added a LICENSE file to the project so that you guys can clone this repo and use the resulting executable without having legal concerns. mold is now available under the GNU AGPLv3, which is an OSI-approved open-source license. You can copy, build, use, distribute or make any modifications to a forked copy as long under the terms of AGPLv3.

**Comment by ssokolow** [comment]
Thanks. I'll put trying it out on the tail end of the TODO list I'm hoping to reach the end of today.

**Comment by joshcangit** [comment]
I guess **AGPLv3** is OK.

This project obviously needs to be kept under a permissive license.
I think having **Apache-2.0** is better.
Maybe even MIT license.

@rui314 you seem to suggest selling this project under a copyright license.

**Comment by rui314** [comment]
I haven't decided anything, but I understand your concern. At the same time, I want you to understand that I've spent hundreds of thousands dollars if not a million for this project already if you include opportunity costs. When you ask me to relicense it under Apache or MIT, you are asking me to give it up completely and effectively donate it to the public for free. I'd like you to take a moment to realize that.

I'll freeze this bug since this isn't a bug.
