### ISSUE TITLE
elflint issues

### ISSUE THREAD

**Issue by marxin** [rui314/mold#805]
I noticed `elflint` from `elfutils`[^1] complains about various things:

```
$ cat a.c
#include <string.h>

int main(int argc, char **argv)
{
  return strcmp (argv[0], "pes") == 0;
}
$ gcc-12 a.c -B ~/Programming/mold/objdir/
$ ./elflint a.out
section [ 6] '.dynsym': symbol 2 (strcmp): unknown type
section [24] '.relro_padding' has wrong type: expected REL, is NOBITS
section [24] '.relro_padding' has wrong flags: expected none and possibly ALLOC|INFO_LINK, is WRITE|ALLOC
section [24] '.relro_padding' not fully contained in segment of program header entry 3
section [24] '.relro_padding' has type NOBITS but is read from the file in segment of program header entry 3
section [29] '.bss' has type NOBITS but is read from the file in segment of program header entry 3
section [31] '.symtab': symbol 63 (__ehdr_start): st_value out of bounds
section [31] '.symtab': _DYNAMIC symbol size 0 does not match dynamic segment size 480
section [31] '.symtab': _GLOBAL_OFFSET_TABLE_ symbol size 0 does not match .got.plt section size 32
section [31] '.symtab': symbol 71 (__executable_start): st_value out of bounds
section [31] '.symtab': symbol 84 (_TLS_MODULE_BASE_): st_value out of bounds
section [38] '.debug_line_str' has wrong flags: expected MERGE|STRINGS, is none
section [40] '.debug_str' has wrong flags: expected MERGE|STRINGS, is none
```

[^1]: https://sourceware.org/git/?p=elfutils.git;a=blob;f=src/elflint.c;h=565cffdc6579ece072f2a708b721666e4ab3f449;hb=HEAD

**Comment by rui314** [comment]
All these are not really errors. `elflint`'s assumption is too strict that it prints out a few error messages for a GNU ld's output. That's probably by design as it's a `lint` tool though.

I don't know why `strip` moves `.shstrtab` to the very end of a file. But it looks like it's working (`.shstrtab` contains section names, so the fact that you can see the section table using `readelf` means that the section can be referenced correctly), so I'm not worried about.

**Comment by marxin** [comment]
> section [ 6] '.dynsym': symbol 2 (strcmp): unknown type

About this one:

```
$ readelf -sW a.out | grep strcmp
     2: 0000000000000000     0 <OS specific>: 10 GLOBAL DEFAULT  UND strcmp@GLIBC_2.2.5 (2)
...
```

Is it really correct the `<OS specific>: 10` as `Type` of the symbol?

**Comment by marxin** [comment]
> That's probably by design as it's a `lint` tool though.

All right, I'm going to report that to elfutils so that these can be probably relaxed for other linkers.

**Comment by rui314** [comment]
`<OS specific>: 10` means GNU ifunc symbol. readelf doesn't pretty print that number unless ELF header's `EI_OSABI` is sett o `ELFOSABI_GNU`. We don't bother to set a value to that field because runtime doesn't care about it and even `readelf` shouldn't care about that too. A symbol with the symbol type 10 is always GNU ifunc.

**Comment by marxin** [comment]
> We don't bother to set a value to that field because runtime doesn't care about it and even `readelf` shouldn't care about that too. A symbol with the symbol type 10 is always GNU ifunc.

All right, so can you please file binutils bug for it? Note, similarly is affected `eu-readelf`:

```
Symbol table [ 5] '.dynsym' contains 3 entries:
 1 local symbol  String table: [ 6] '.dynstr'
  Num:            Value   Size Type    Bind   Vis          Ndx Name
...
    2: 0000000000000000      0 LOOS+0  GLOBAL DEFAULT    UNDEF strcmp@GLIBC_2.2.5 (2)
```

**Comment by rui314** [comment]
Filed a bug to binutils: https://sourceware.org/bugzilla/show_bug.cgi?id=29718

**Comment by rui314** [comment]
Yeah, I saw that. It's unfortunate, but I think this is an "agree to disagree" situation. The only tools that complains this is introspection tools (readelf and elflint), and all real-world systems seem to be working fine without it, so we don't have a reason to take a risk to change our output.

Ideally, we should update the ELF specification to document popular GNU extensions such as GNU ifunc or .gnu.hash as optional extensions. I don't think it's doable because of the lack of ownership of the spec, though.

**Comment by marxin** [comment]
> Yeah, I saw that. It's unfortunate, but I think this is an "agree to disagree" situation. The only tools that complains this is introspection tools (readelf and elflint), and all real-world systems seem to be working fine without it, so we don't have a reason to take a risk to change our output.

What risks can you see? Btw. the linker should respect ABI chosen by an object:

mvc.C:
```c++
__attribute__((target_clones("arch=core-avx2", "default"))) void foo() {}
int main() { foo(); return 0; }
```

```
$ g++ mvc.C -c && readelf -h mvc.o | grep OS 
  OS/ABI:                            UNIX - GNU
$ gcc mvc.o && readelf -h a.out | grep OS
  OS/ABI:                            UNIX - System V
```

Is it something mold should handle?
