### ISSUE TITLE
Wrong code with IFUNC and resolvers

### ISSUE THREAD

**Issue by marxin** [rui314/mold#830]
Also isolated from Binutils:

```
wget https://raw.githubusercontent.com/bminor/binutils-gdb/master/ld/testsuite/ld-x86-64/pr20253-2a.c
wget https://raw.githubusercontent.com/bminor/binutils-gdb/master/ld/testsuite/ld-x86-64/pr20253-2b.S
wget https://raw.githubusercontent.com/bminor/binutils-gdb/master/ld/testsuite/ld-x86-64/pr20253-2c.S
wget https://raw.githubusercontent.com/bminor/binutils-gdb/master/ld/testsuite/ld-x86-64/pr20253-2d.S

gcc-12 *[cS] && ./a.out
PASS

gcc-12 *[cS] -B ~/Programming/mold/objdir/ && ./a.out
Aborted (core dumped)
```

**Comment by ishitatsuyuki** [comment]
I've checked this test and it seems it's expecting `func_pointer_to_ifunc` to be equal to the resolved function. This is true for bfd, but in mold we just relocate it to the PLT entry instead.

The code is not wrong, just one more indirection.

The reasoning to use a PLT indirection instead of directly relocating (#466) also applies here: To statically relocate the function pointer, we need to introduce an extra dynamic relocation, which increases startup cost and most importantly dirtying the relocated page.

Note that most of the time you take a function pointer the compiler is already generating a GOTPCRELX, which should make this a non-problem.

I think this probably can be closed safely.
