### ISSUE TITLE
Mold not receiving arguments passed to mold through -Wl on MacOS

### ISSUE THREAD

**Issue by atw1020** [rui314/mold#866]
Mold responds differently to arguments passed directly through the command line vs. arguments forwarded to Mold via -Wl in clang. 

When mold is run directly, the "--version" argument is recognized:
```
$ mold --version
mold 1.6.0 (compatible with GNU ld)
$ 
```

But when sent through clang, mold does not recognize "--version"
```
$ clang -Wl,--version -fuse-ld=mold
mold: fatal: unknown command line option: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm running MacOS 13.0 with Apple clang version 14.0.0. Hope this helps!

**Comment by ZhongRuoyu** [comment]
That's because on macOS, `clang` invokes `ld64.mold` instead of `ld.mold`. `ld64.mold` is a Mach-O linker, which is intended to be a drop-in replacement of Apple's ld. Apple's ld (the `ld` on your system) does not support `--version`, so neither does mold [^1].

If you invoke mold as `mold` or `ld.mold`, then mold behaves as an ELF linker, which *does* support the `-v` flag. Hence the difference you observed.

[^1]: https://github.com/rui314/mold/pull/640#issuecomment-1220307291
