### ISSUE TITLE
C++20: C++17 or at least make it configure failure?

### ISSUE THREAD

**Issue by okias** [rui314/mold#936]
On Debian stable (CI), with 1.8.0 I'm getting:
```
In file included from /tmp/clone/mold/third-party/rust-demangle/rust-demangle.c:4:
/tmp/clone/mold/inttypes.h:23:10: fatal error: bit: No such file or directory
   23 | #include <bit>
      |          ^~~~~
compilation terminated.
```
which is probably think I didn't noticed that C++20 is needed (`Standard library header <bit> (C++20)`). Previously 1.6.0 worked with C++17 (while I think you had C++20 in Readme anyway).

First, could CMake fail when C++20-ready compiler isn't present? (to make it more obvious, C++20 is pretty new)

Second, we currently cannot move from Debian `bullseye` (in month or two, it'll be possible, but not for now). So if `mold` could be compatible with C++17, it would be amazing (and I'm the big fan of using latest std! :wink: )

We're at mold 1.6.0 now which works great, but with enabling --gdb-index it started to fail on s390x with [segmentation fault in linker](https://gitlab.freedesktop.org/mesa/mesa/-/jobs/33993382#L782)

**Comment by Alcaro** [comment]
That is a quite strange error, considering current Debian stable has 10.2.1 and 11.0.1, respectively. <bit> is supported since GCC 9 and Clang 9.

The former question is nontrivial - what does "C++20-ready compiler" mean? GCC and Clang support -std=c++20 since 10.1 and 10.0.0, respectively, which are too old (mold's readme asks for GCC 10.2 or Clang 12.0.0). But if you ask for something that supports the entire C++20, [you can't use any version of GCC or Clang at all.](https://en.cppreference.com/w/cpp/compiler_support/20)

Adding a version check on GCC >= 10.2 or Clang >= 12.0.0 would be plausible, but would fail on weird environments like Android/Termux and AppleClang that use weird frankenstein versions. May be worth trying, though.

Last time I checked, Rui was [skeptical to backporting mold to older compilers](https://github.com/rui314/mold/issues/603#issuecomment-1209147022), so I don't think C++17 is likely.

**Comment by rui314** [comment]
I usually request users to use a newer version of their C++ compiler if it cannot compile mold's source files, but it looks like <bit> is especially problematic for some reason, I can make a change to eliminate the use of the header. I actually did it before, but I re-introduced that header again as I didn't remember what was the problem.

Being said that, I'm not sure if mold can be built with your compiler even without <bit>, as mold depends on lots of other C++20 features.

**Comment by rui314** [comment]
I reverted my previous commit because it broke our CI and I cannot reproduce the failure on my local machine. Given the situation, it is probably better to ask users to just use a recent version of a C++ compiler. Or you can use our binary packages available at https://github.com/rui314/mold/releases/tag/v1.8.0. Doesn't that work for you?

**Comment by okias** [comment]
Ok, I think I see the issue. It's not about C++20, it's about `.c` files using c++ features in `rust-demangle/rust-demangle.c`

**Comment by rui314** [comment]
Ah, okay, we have https://github.com/rui314/mold/blob/main/inttypes.h whose name collides with the standard `inttypes.h` header. I'll rename our own file.

**Comment by okias** [comment]
exactly the place where I am looking right now :) Thank you @rui314 (and @Alcaro )

**Comment by okias** [comment]
@rui314 before you commit, let me test the patch, since with previous one it still fails at 
```
In file included from /tmp/clone/mold/third-party/rust-demangle/rust-demangle.c:4:
/tmp/clone/mold/inttypes.h:23:10: fatal error: cstdint: No such file or directory
```

**Comment by okias** [comment]
@rui314 yeah, build is fixed right now. Thank you again!
